### ISSUE TITLE
Can't configure backup correctly -> Endpoint and Region 

### ISSUE THREAD

**Issue by adrien-barret** [percona/percona-xtradb-cluster-operator#1723]
### Report

I have set a backup on my DB configuration using custom values and deployment. It seems that the endpoint and default region is not took correctly in env as the values keep to be:
```
│       ACCESS_KEY_ID:      <set to the key 'AWS_ACCESS_KEY_ID' in secret 'mysql-s3-backup-secret'>      Optional: false                                                                                           │4s         │                                                               │
│       SECRET_ACCESS_KEY:  <set to the key 'AWS_SECRET_ACCESS_KEY' in secret 'mysql-s3-backup-secret'>  Optional: false                                                                                           │64s        │                                                               │
│       DEFAULT_REGION:     us-west-2                                                                                                                                                                              │108m       │                                                               │
│       ENDPOINT:           https://sfo2.digitaloceanspaces.com 
```
whatever I put as region or endpoint the values doesn't change. I tried by the config and by the env variables but still the same.

I use a gcp bucket which is compaptible but I needed to change my secret to use `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` instead of `credentialsAccessKey/credentialsSecretKey` refered into the values.yaml. using the key refered into the values lead to a secret not found, it's a second problem but still...

### More about the problem

my values file:

```yaml
backup:
  enabled: true
  # allowParallel: true
  image:
    repository: percona/percona-xtradb-cluster-operator
    tag: 1.14.0-pxc8.0-backup-pxb8.0.35
  # backoffLimit: 6
  # serviceAccountName: percona-xtradb-cluster-operator
  # imagePullPolicy: Always
  imagePullSecrets: []
  # - name: private-registry-credentials
  pitr:
    enabled: false
    storageName: s3-us-west-binlogs
    timeBetweenUploads: 60
    timeoutSeconds: 60
    resources:
      requests: {}
      limits: {}
  storages: 
    s3-us-central1:
      type: s3
      s3:
        bucket: myapp-gcp-bucket
        # Use credentialsSecret OR credentialsAccessKey/credentialsSecretKey
        credentialsSecret: mysql-s3-backup-secret     
        region: us-central1
        endpointUrl: https://storage.googleapis.com
      containerOptions:
        env:        
        - name: DEFAULT_REGION
          value: us-central1                                                                                                                                                                              
        - name: ENDPOINT
          value: https://storage.googleapis.com
```

### Steps to reproduce

1. deploy the operator with helm
2. deploy the bd with helm and override the values with the example above
3. check if the backup is working

### Versions

1. Kubernetes: 1.29.1
2. Operator: latest
3. Database: 1.14.0-pxc8.0-backup-pxb8.0.35
