### ISSUE TITLE
Not possible to set imagePullSecrets for sidecars

### ISSUE THREAD

**Issue by gtirloni** [percona/percona-xtradb-cluster-operator#1728]
### Report

While using a private container registry with authentication, I noticed that it's not possible to specify `imagePullSecrets` in the `pxc` CRD for sidecars (e.g. mysqld-exporter).

### More about the problem

Sidecars fail to pull image from private repository.

### Steps to reproduce

```yaml
pxc:
  sidecars:
    - name: mysqld-exporter
      image: some.private.registry/mysqld-exporter
      imagePullSecrets:
        - name: secret_name
```

### Versions

1. Kubernetes: 1.28
2. Operator: 1.14
3. Database: MySQL 8.0.32-24.2
