### ISSUE TITLE
XTRADB Pods OOMkilled with limit and without limit the always use 16GB of memory

### ISSUE THREAD

**Issue by Elyytscha** [percona/percona-xtradb-cluster-operator#1819]
### Report

cr:

```
apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: sys-stat-db-cluster
  namespace: database
spec:
  allowUnsafeConfigurations: true
  crVersion: 1.11.0
  enableCRValidationWebhook: true
  haproxy:
    enabled: false
  proxysql:
    enabled: true
    gracePeriod: 30
    image: 'percona/percona-xtradb-cluster-operator:1.11.0-proxysql'
    imagePullPolicy: Always
    podDisruptionBudget:
      maxUnavailable: 1
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1G
  pxc:
    configuration: |
      [mysqld]

      innodb_buffer_pool_size=1G
    image: 'percona/percona-xtradb-cluster:5.7'
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1G
  secretsName: system-status-xtradb-cluster-secrets
  upgradeOptions:
    apply: disabled
    schedule: 0 4 * * *
 ```

we already tried the newest version of the operator 1.15, it has the exact same behaviour, it alwas uses 16gb ram, we can not get it to fit a size for a small db, we want that it uses max 2gb ram because its only a test database which definitely does not need 16gb ram x3

when we add

```
  pxc:
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 2Gi
```
it just gets oomkilled because it wants to use again 16gb of memory.

![image](https://github.com/user-attachments/assets/c1a1758f-2408-4975-972b-adcd8a8c8fce)
![image](https://github.com/user-attachments/assets/7449b961-d7f1-4b51-afec-28ca21755ff1)

   

### More about the problem

expected behaviour: no oomkill

### Steps to reproduce

1. use the provided cr and try to set limits

### Versions

1. 1.28.x
2. 1.11 - 1.15
3. 5.7.x
