### ISSUE TITLE
Operator fails reconciling database spec with LoadBalancerSourceRanges specified

### ISSUE THREAD

**Issue by gwvandesteeg** [percona/percona-xtradb-cluster-operator#1899]
### Report

When attempting to reconcile a chart defined with
```
    haproxy:
      enabled: true
      exposePrimary:
        enabled: true
        type: LoadBalancer
        loadBalancerSourceRanges:
          - 10.0.0.0/8
```
The reconciliation fails.

### More about the problem

Pod logs
```
2024-12-05T04:10:19.467Z        ERROR   Reconciler error        {"controller": "pxc-controller", "namespace": "default", "name": "mysql-pxc-db", "reconcileID": "1215ff06-2c03-4a92-b8f7-97eca57198c9", "error": "mysql-pxc-db-haproxy-replicas upgrade error: Service \"mysql-pxc-db-haproxy-replicas\" is invalid: spec.LoadBalancerSourceRanges: Forbidden: may only be used when `type` is 'LoadBalancer'", "errorVerbose": "Service \"mysql-pxc-db-haproxy-replicas\" is invalid: spec.LoadBalancerSourceRanges: Forbidden: may only be used when `type` is 'LoadBalancer'\nmysql-pxc-db-haproxy-replicas upgrade error\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).reconcileHAProxy\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/controller.go:515\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).Reconcile\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/controller.go:366\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1695"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:324
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:261
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222
```

### Steps to reproduce

1.  Create chart with a valid loadBalancerSourceRanges specified
2.  Update the chart by changing something simple like an annotation
3. Poof, failure.

### Versions

1. Kubernetes:
```
$ kubectl version
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.31.2-eks-7f9249a
```
2. Operator (Fails with both charts for v1.15.0 and v1.15.1)
```
$ kubectl logs -n pxc-operator mysql-operator-bc8dcc85d-zwtr7 -f
2024-12-05T01:18:51.956Z        INFO    setup   Runs on {"platform": "kubernetes", "version": "v1.31.2-eks-7f9249a"}
2024-12-05T01:18:51.956Z        INFO    setup   Manager starting up     {"gitCommit": "9807f08b1c46ffdf141fb9935e36bb09cd7edefe", "gitBranch": "release-1-15-1", "buildTime": "2024-10-14T17:02:29Z", "goVersion": "go1.22.8", "os": "linux", "arch": "amd64"}
```
3. Database (pxc chart version: v1.15.0)
```
image: percona/percona-xtradb-cluster:8.0.36-28.1
```

### Anything else?

This is not the only thing broken upon reconciliation, with a reconciliation failure backup tasks/jobs don't get created/updated.

**Comment by gwvandesteeg** [comment]
Appears to be related to this code:
https://github.com/percona/percona-xtradb-cluster-operator/blob/a7a036d04ee345b013e9136977d7a5f4cf958f32/pkg/pxc/service.go#L429-L444

**Comment by hors** [comment]
@gwvandesteeg thank you! I have create jira task for this bug https://perconadev.atlassian.net/browse/K8SPXC-1538

**Comment by gwvandesteeg** [comment]
What's the progress here? It has been a few months, do I need to write the patch myself here and hope it works or is this likely to get fixed soon. This is one bug that completely and utterly breaks the functionality of the PXC operator and makes it unusable.

**Comment by dbazhenov** [comment]
@gwvandesteeg thank you for waiting and reminding us

The bug has been fixed and released in version 1.17.0
https://docs.percona.com/percona-operator-for-mysql/pxc/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.17.0.html#improvements

Thanks for reporting bugs!

**Comment by gwvandesteeg** [comment]
The issue has not been fixed satisfactorily.

Version details:

```
$ kubectl logs -f -n pxc-operator mysql-operator-69b4c7f96f-t46kq
2025-05-16T01:34:04.322Z        INFO    setup   Runs on {"platform": "kubernetes", "version": "v1.31.7-eks-bcf3d70"}
2025-05-16T01:34:04.322Z        INFO    setup   Manager starting up     {"gitCommit": "864c5b6361ff477546b39f0695db5ee259c85269", "gitBranch": "release-1-17-0", "buildTime": "2025-04-07T14:08:55Z", "goVersion": "go1.23.8", "os": "linux", "arch": "amd64"}
```

It cannot reconcile pre-existing service definitions from versions prior to 1.17.0, re-creating the LoadBalancer Service is not a suitable resolution since that would likely change all the IPs associated with the LoadBalancers causing a service interruption for connectivity to the database server.

```
2025-05-16T01:34:26.139Z        ERROR   Reconciler error        {"controller": "pxc-controller", "namespace": "default", "name": "voipmonitor-db-pxc-db", "reconcileID": "d8d0273b-af92-4c64-b78a-593a100078ac", "error": "voipmonitor-db-pxc-db-haproxy upgrade error: Service \"voipmonitor-db-pxc-db-haproxy\" is invalid: spec.loadBalancerClass: Invalid value: \"null\": may not change once set", "errorVerbose": "Service \"voipmonitor-db-pxc-db-haproxy\" is invalid: spec.loadBalancerClass: Invalid value: \"null\": may not change once set\nvoipmonitor-db-pxc-db-haproxy upgrade error\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).reconcileHAProxy\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/controller.go:558\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).Reconcile\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/controller.go:429\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:334\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:347
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255
```

The current spec state of the Service is below
```
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.129.248
  clusterIPs:
  - 172.20.129.248
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerClass: service.k8s.aws/nlb
  loadBalancerSourceRanges:
  - 10.0.0.0/8
  ports:
  - name: mysql
    nodePort: 30273
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: proxy-protocol
    nodePort: 31977
    port: 3309
    protocol: TCP
    targetPort: 3309
  - name: mysql-admin
    nodePort: 30702
    port: 33062
    protocol: TCP
    targetPort: 33062
  - name: mysqlx
    nodePort: 30844
    port: 33060
    protocol: TCP
    targetPort: 33060
  selector:
    app.kubernetes.io/component: haproxy
    app.kubernetes.io/instance: voipmonitor-db-pxc-db
    app.kubernetes.io/name: percona-xtradb-cluster
  sessionAffinity: None
  type: LoadBalancer
```
