### ISSUE TITLE
Proxysql auto-generated password for `proxysqladmin` can start with an invalid character

### ISSUE THREAD

**Issue by fideloper** [percona/percona-xtradb-cluster-operator#1961]
### Report

Operator version: 1.16.1

We spin up mysql databases often via PXC. When using proxysql (over haproxy), it's possible for a `proxysqladmin` generated password to start with a `*` character, which seems to be the cause of a proxysql error.

![Image](https://github.com/user-attachments/assets/622d5b9c-8fc3-4528-b11e-9e1b71375438)

When this happens, proxysl assumes the password is hashed as per this gem from 2018 I found 😂 https://groups.google.com/g/proxysql/c/oUBc1-CaHR4/m/1O33RwidCgAJ

### More about the problem

proysql logs:

This repeats over and over
```
proxysql 2025-01-29 15:09:32 MySQL_encode.cpp:152:decode_char(): [ERROR] Invalid char2025-01-29 15:09:32 MySQL_encode.cpp:152:decode_char(): [ERROR] Invalid char2025-01-29 15:09:32 MySQL_encode.cpp:152:decode_char(): 
```

As a result, the Operator contains this reconcile error:

```
pxc-operator-67bd46b68-fggkp 2025-01-29T15:08:21.146Z    ERROR    sync users    {"controller": "pxc-controller", "namespace": "db-87654321-4321-4321-4321-210987654321", "name": "db-1", "reconcileID": "edd1 │
│ e6ed-b906-4bab-abfe-105f2d2c3c5b", "error": "exec syncusers: failed to execute command in pod: command terminated with exit code 1 /  / ERROR 1045 (28000): ProxySQL Error: Access denied for user 'proxyadmin'@'127.0.0.1'  │
│ (using password: YES)\nERROR (line:339) : ProxySQL connection check failed. \n-- Could not connect to ProxySQL at localhost:6032 \n-- Please check the ProxySQL connection parameters and status.\nERROR 1045 (28000): Proxy │
│ SQL Error: Access denied for user 'proxyadmin'@'127.0.0.1' (using password: YES)\nERROR (line:339) : ProxySQL connection check failed. \n-- Could not connect to ProxySQL at localhost:6032 \n-- Please check the ProxySQL c │
│ onnection parameters and status.\nERROR 1045 (28000): ProxySQL Error: Access denied for user 'proxyadmin'@'127.0.0.1' (using password: YES)\nERROR (line:339) : ProxySQL connection check failed. \n-- Could not connect to  │
│ ProxySQL at localhost:6032 \n-- Please check the ProxySQL connection parameters and status.\nERROR 1045 (28000): ProxySQL Error: Access denied for user 'proxyadmin'@'127.0.0.1' (using password: YES)\nERROR (line:339) : P │
│ roxySQL connection check failed. \n-- Could not connect to ProxySQL at localhost:6032 \n-- Please check the ProxySQL connection parameters and status.\nERROR 1045 (28000): ProxySQL Error: Access denied for user 'proxyadm │
│ in'@'127.0.0.1' (using password: YES)\nERROR (line:339) : ProxySQL connection check failed. \n-- Could not connect to ProxySQL at localhost:6032 \n-- Please check the ProxySQL connection parameters and status.\n", "error │
│ Verbose": "exec syncusers: failed to execute command in pod: command terminated with exit code 1 /  / ERROR 1045 (28000): ProxySQL Error: Access denied for user 'proxyadmin'@'127.0.0.1' (using password: YES)\nERROR (line │
│ :339) : ProxySQL connection check failed. \n-- Could not connect to ProxySQL at localhost:6032 \n-- Please check the ProxySQL connection parameters and status.\nERROR 1045 (28000): ProxySQL Error: Access denied for user  │
│ 'proxyadmin'@'127.0.0.1' (using password: YES)\nERROR (line:339) : ProxySQL connection check failed. \n-- Could not connect to ProxySQL at localhost:6032 \n-- Please check the ProxySQL connection parameters and status.\n │
│ ERROR 1045 (28000): ProxySQL Error: Access denied for user 'proxyadmin'@'127.0.0.1' (using password: YES)\nERROR (line:339) : ProxySQL connection check failed. \n-- Could not connect to ProxySQL at localhost:6032 \n-- Pl │
│ ease check the ProxySQL connection parameters and status.\nERROR 1045 (28000): ProxySQL Error: Access denied for user 'proxyadmin'@'127.0.0.1' (using password: YES)\nERROR (line:339) : ProxySQL connection check failed. \ │
│ n-- Could not connect to ProxySQL at localhost:6032 \n-- Please check the ProxySQL connection parameters and status.\nERROR 1045 (28000): ProxySQL Error: Access denied for user 'proxyadmin'@'127.0.0.1' (using password: Y │
│ ES)\nERROR (line:339) : ProxySQL connection check failed. \n-- Could not connect to ProxySQL at localhost:6032 \n-- Please check the ProxySQL connection parameters and status.\n\ngithub.com/percona/percona-xtradb-cluster │
│ -operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).syncPXCUsersWithProxySQL\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/users.go:925\ngithub.com/percona/percona-xtradb-clus │
│ ter-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).resyncPXCUsersWithProxySQL.func1\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/controller.go:1025\nruntime.goexit\n\t/us │
│ r/local/go/src/runtime/asm_amd64.s:1700"} 
```

Proxysql is never, therefore, configured.

### Steps to reproduce

This cluster reproduced it for me. Note that I create the secret ahead of time, being sure to set `proxysqladmin` user's password to start with a `*`

```yaml
apiVersion: v1
data:
  monitor: ISswWlI+PyFaIVd7QmxhS1B5
  operator: Y2J5d1VxI1p3SywpKEJkOU5b
  # password: *eH{m^S%]x2)=,vSknK
  proxyadmin: KmVIe21eUyVdeDIpPSx2U2tuSw==
  replication: KTdBcU0wc1NJRXt+cj5ndjlR
  root: RUYzczJEeVUtQGxsZXVxaC1TSQ==
  xtrabackup: N10hZ09WZEZweUlfJSs0PntS
kind: Secret
metadata:
  name: db-1-secrets
  namespace: default
type: Opaque
---
apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: cluster1
  namespace: default
  finalizers:
    - percona.com/delete-pxc-pods-in-order
    - percona.com/delete-ssl
    - percona.com/delete-proxysql-pvc
    - percona.com/delete-pxc-pvc
spec:
  crVersion: 1.16.1
  enableVolumeExpansion: true
  secretsName: db-1-secrets
  tls:
    enabled: false
  unsafeFlags:
    tls: false
    pxcSize: true
    proxySize: true
#    backupIfUnhealthy: false
#  pause: false
  updateStrategy: SmartUpdate
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: disabled
    schedule: "0 4 * * *"
  pxc:
    size: 1
    image: perconalab/percona-xtradb-cluster-operator:main-pxc8.0
    autoRecovery: true
    configuration: |
      [mysqld]
      performance_schema=OFF
    resources:
      requests:
        memory: 1000M
        cpu: "0.125"
#        ephemeral-storage: 1G
      limits:
        memory: 1000M
        cpu: "0.5"
#        ephemeral-storage: 1G
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      maxUnavailable: 1
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6G
    gracePeriod: 600
  haproxy:
    enabled: false
    size: 3
    image: perconalab/percona-xtradb-cluster-operator:main-haproxy
    resources:
      requests:
        memory: 1G
        cpu: 600m
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      maxUnavailable: 1
    gracePeriod: 30
  proxysql:
    enabled: true
    size: 1
    image: perconalab/percona-xtradb-cluster-operator:main-proxysql
    resources:
      requests:
        memory: 1G
        cpu: 600m
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2G
    podDisruptionBudget:
      maxUnavailable: 1
    gracePeriod: 30
  logcollector:
    enabled: false
    image: perconalab/percona-xtradb-cluster-operator:main-logcollector
    resources:
      requests:
        memory: 100M
        cpu: 200m
  pmm:
    enabled: false
    image: perconalab/pmm-client:dev-latest
    serverHost: monitoring-service
    resources:
      requests:
        memory: 150M
        cpu: 300m
  backup:
    image: perconalab/percona-xtradb-cluster-operator:main-pxc8.0-backup
    pitr:
      enabled: false
      storageName: STORAGE-NAME-HERE
      timeBetweenUploads: 60
      timeoutSeconds: 60
    storages:
    schedule:

```

### Versions

1. Kubernetes
2. Operator
3. Database

### Anything else?

Solutions would involve editing this logic: https://github.com/percona/percona-xtradb-cluster-operator/blob/acc4ac6fbe9ddfb9cf95721a08aded155843195c/pkg/controller/pxc/secrets.go#L103

...to either disallow a `*` character, or to add logic to ensure `*` isn't the first character (perhaps specifically for proxysqladmin user?)

**update**: proxysql already has its own extra validation ( I guess it loves being special ) so we can just tuck that logic in there. https://github.com/percona/percona-xtradb-cluster-operator/blob/acc4ac6fbe9ddfb9cf95721a08aded155843195c/pkg/controller/pxc/secrets.go#L127
