### ISSUE TITLE
Creating users trough CRD isn't working with helm

### ISSUE THREAD

**Issue by Juoper** [percona/percona-xtradb-cluster-operator#1967]
### Report

when starting percona xtradb cluster with the following yaml secrets for users are not created

### More about the problem

no secrets with the users are created

### Steps to reproduce

1. apply the following cluster:

```
annotations: {}
backup:
  enabled: true
  image:
    repository: percona/percona-xtradb-cluster-operator
    tag: 1.16.1-pxc8.0-backup-pxb8.0.35
  imagePullSecrets: null
  pitr:
    enabled: false
    resources:
      limits: {}
      requests: {}
    storageName: s3-us-west-binlogs
    timeBetweenUploads: 60
    timeoutSeconds: 60
  schedule: null
  storages: {}
crVersion: 1.16.1
enableCRValidationWebhook: false
enableVolumeExpansion: false
finalizers:
  - percona.com/delete-pxc-pods-in-order
fullnameOverride: ''
haproxy:
  affinity:
    antiAffinityTopologyKey: kubernetes.io/hostname
  annotations: {}
  enabled: true
  gracePeriod: 30
  image: percona/haproxy:2.8.11
  imagePullSecrets: null
  labels: {}
  livenessDelaySec: 300
  livenessProbes:
    failureThreshold: 4
    initialDelaySeconds: 60
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 5
  nodeSelector: {}
  podDisruptionBudget:
    maxUnavailable: 1
  readinessDelaySec: 15
  readinessProbes:
    failureThreshold: 3
    initialDelaySeconds: 15
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1
  resources:
    limits: {}
    requests:
      cpu: 600m
      memory: 1G
  sidecarPVCs: null
  sidecarResources:
    limits: {}
    requests: {}
  sidecarVolumes: null
  sidecars: null
  size: 3
  tolerations: null
ignoreAnnotations: null
ignoreLabels: null
logcollector:
  enabled: true
  image: percona/percona-xtradb-cluster-operator:1.16.1-logcollector-fluentbit3.2.2
  imagePullSecrets: null
  resources:
    limits: {}
    requests:
      cpu: 200m
      memory: 100M
nameOverride: ''
operatorImageRepository: percona/percona-xtradb-cluster-operator
pause: false
pmm:
  enabled: false
  image:
    repository: percona/pmm-client
    tag: 2.44.0
  imagePullSecrets: null
  resources:
    limits: {}
    requests:
      cpu: 300m
      memory: 150M
  serverHost: monitoring-service
  serverUser: admin
proxysql:
  affinity:
    antiAffinityTopologyKey: kubernetes.io/hostname
  annotations: {}
  enabled: false
  gracePeriod: 30
  image: percona/proxysql2:2.7.1
  imagePullSecrets: null
  labels: {}
  livenessDelaySec: 300
  nodeSelector: {}
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    size: 8Gi
  podDisruptionBudget:
    maxUnavailable: 1
  readinessDelaySec: 15
  resources:
    limits: {}
    requests:
      cpu: 600m
      memory: 1G
  sidecarPVCs: null
  sidecarResources:
    limits: {}
    requests: {}
  sidecarVolumes: null
  sidecars: null
  size: 3
  tolerations: null
pxc:
  affinity:
    antiAffinityTopologyKey: kubernetes.io/hostname
  annotations: {}
  autoRecovery: true
  certManager: false
  gracePeriod: 600
  image:
    repository: percona/percona-xtradb-cluster
    tag: 8.4.3-3.1
  imagePullSecrets: null
  labels: {}
  livenessDelaySec: 300
  livenessProbes:
    failureThreshold: 3
    initialDelaySeconds: 300
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  nodeSelector: {}
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    size: 8Gi
  podDisruptionBudget:
    maxUnavailable: 1
  readinessDelaySec: 15
  readinessProbes:
    failureThreshold: 5
    initialDelaySeconds: 15
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 15
  resources:
    limits: {}
    requests:
      cpu: 600m
      memory: 1G
  sidecarPVCs: null
  sidecarResources:
    limits: {}
    requests: {}
  sidecarVolumes: null
  sidecars: null
  size: 3
  tolerations: null
secrets:
  tls: {}
tls:
  enabled: true
updateStrategy: SmartUpdate
upgradeOptions:
  apply: disabled
  schedule: 0 4 * * *
  versionServiceEndpoint: https://check.percona.com
global:
  cattle:
    clusterId: local
    clusterName: local
    rkePathPrefix: ''
    rkeWindowsPathPrefix: ''
    systemProjectId: p-xbr55
    url: https://lab.thanner.dev
users:
  - name: my-user-two

```

### Versions

1. Kubernetes 1.31.2
2. Operator 1.16.1
3. Database
