### ISSUE TITLE
PITR crashes on "ERROR: collect binlog files: get GTID sets: get GTID set: scan set: context deadline exceeded"

### ISSUE THREAD

**Issue by franklouwers** [percona/percona-xtradb-cluster-operator#2012]
### Report

Hi,

I'm trying to enable PITR backups in my pxc cluster. The PITR pod crashes with:

```
masked-pxc-db-pitr-d6cf45989-gfr2d pitr 2025/03/28 10:11:26 run binlog collector
masked-pxc-db-pitr-d6cf45989-gfr2d pitr 2025/03/28 10:11:27 Reading binlogs from pxc with hostname= masked-pxc-db-pxc-0.masked-pxc-db-pxc.percona.svc.cluster.local
masked-pxc-db-pitr-d6cf45989-gfr2d pitr 2025/03/28 10:12:26 ERROR: collect binlog files: get GTID sets: get GTID set: scan set: context deadline exceeded
```

### More about the problem
note the extra ` ` after `hostname=`

### Steps to reproduce

1. install pxc-operator-1.16.1 via helm
2. Create a PXC cluster with following backup section in the config:

```
backup:
  pitr:
    enabled: true
    timeBetweenUploads: 60
    storageName: aws-bucket-pitr
  schedule:
    - keep: 90
      name: daily
      schedule: 4 15 * * *
      storageName: aws-bucket-backups
  storages:
    aws-bucket-backups:
      s3:
        bucket: ${backup_bucket}/backups
        region: ${backup_region}
        credentialsSecret: ${backup_credentials_secret_name}
      type: s3
    aws-bucket-pitr:
      s3:
        bucket: ${backup_bucket}/pitr
        region: ${backup_region}
        credentialsSecret: ${backup_credentials_secret_name}
      type: s3
```

3. Watch pitr crash

### Versions

1. Kubernetes: v1.31.6-eks-bc803b4
2. Operator: 1.16.1 (via helm)
3. Database: 8.0.39-30.1
