### ISSUE TITLE
Cannot backup to S3 provider (Backblaze) due to missing S3 options

### ISSUE THREAD

**Issue by ToshY** [percona/percona-xtradb-cluster-operator#2041]
### Report

**Problem**

Both the `s3` options here, as well as in the Helm chart for `pxc-db` are outdated. There are S3 options needed in order to have working backups for other (semi-) S3-compatible services. 

Since AWS `1.37.0` / `2.23.0`, integrity protection was enabled by default: https://github.com/aws/aws-cli/issues/9214 This causes issues for providers like Backblaze that [do not support](https://www.backblaze.com/docs/cloud-storage-s3-compatible-api#unsupported-features) headers like `x-amz-checksum-algorithm`, leading to errors:

```text
2025/04/19 16:49:21 ERROR: collect binlog files: manage binlog: put binlog.000003 object: put object binlog_1745071805_3037c43d8f1b1bd390e40dba73d07963: Unsupported header 'x-amz-checksum-algorithm' received for this API call.
```

### More about the problem

Options that are missing and causing issues:

- `forcePathStyle` - bucketname part of path / https://github.com/percona/percona-helm-charts/pull/349
- `prefix` - specific directory in bucket / https://github.com/percona/percona-helm-charts/issues/322 / https://github.com/percona/percona-xtradb-cluster-operator/issues/1991
- `checksumAlgorithm` - need to be disabled/empty for Backblaze / https://www.backblaze.com/docs/cloud-storage-s3-compatible-api#unsupported-features

The implementation of S3 backup options seem very inconsistent across different operators. I first read about backup/restore on a blog post here for MongoDB:
https://www.percona.com/blog/percona-operator-for-mongodb-backup-and-restore-on-s3-compatible-storage-backblaze/

If the options that are used in the `percona/percona-server-mongodb-operator` would be implemented here, it would already go a long way: https://github.com/percona/percona-server-mongodb-operator/blob/676b4db0183dc4721ac10ce75cb6981802e78aca/deploy/crd.yaml#L124

### Steps to reproduce

```yaml
backup:
  enabled: true
  image:
    repository: percona/percona-xtradb-cluster-operator
  pitr:
    enabled: true
    storageName: s3-eu-central
    timeBetweenUploads: 300
    timeoutSeconds: 60
  storages:
    s3-eu-central:
      type: s3
      verifyTLS: true
      s3:
        bucket: <bucket-name>
        credentialsSecret: <secret-name>
        region: 'eu-central-003'
        endpointUrl: 'https://s3.eu-central-003.backblazeb2.com'
```

### Versions

1. Kubernetes - `k3s (v1.31.7)`
2. Operator - `percona/percona-xtradb-cluster-operator` ; helm chart `1.17.0`
3. Database - PXC

### Anything else?

p.s. This is the first time using Percona software
